version: 2
jobs:
  build:
    machine: true
    working_directory: '~/cli-test'
    steps:
      - checkout
      - run: docker login -u cult --password-stdin '.>9%@8F8Y\Roz$oK8M'

      # build the application image
      - run: docker build -t cult/cli-test .

      # deploy the image
      - run: docker push cult/cli-test


workflows:
  version: 2
  build:
    jobs:
      - build