version: 2
jobs:
  build:
    machine: true
    working_directory: '~/cli-test'
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      # build the application image
      - run: docker build -t $DOCKER_USER/cli-test .

      # deploy the image
      - run: docker push $DOCKER_USER/cli-test


workflows:
  version: 2
  build:
    jobs:
      - build